#!/bin/python3
# Conditional Statement

def alcohol(age, money):
	if (age > 21) and (money >= 5):
		return "You're getting a drink."
	elif (age > 21) and (money < 5):
		return "You do not have enough money."
	elif (age < 21) and (money >= 5):
		return "Nice try, kiddo!"
	else:
		return "You're too poor and too young!"
print(alcohol(22, 15))
print(alcohol(22, 3))
print(alcohol(18, 100))
print(alcohol(18, 2))
